<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ApplicationIcon>ico\roxami_icon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <IsWebProject>false</IsWebProject>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="wwwroot\**" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="index.html" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>