<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon>..\ico\roxami_icon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>RoxamiStudio_Setup</AssemblyName>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\installer_output\RoxamiStudio_package.zip">
      <LogicalName>RoxamiStudio_Setup.RoxamiStudio_package.zip</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
